#
# Copyright (C) 2017 C-SKY Microsystems
#
# SPDX-License-Identifier:	GPL-2.0+
#
extra-y     += start.o

obj-y       += cpu.o
obj-y       += entry.o
obj-y       += exception.o
obj-y       += interrupt.o
obj-y       += crt0.o
obj-y       += timer.o
obj-y       += cache.o
