#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

extra-y     += start.o

obj-y       += cpu.o
obj-y       += entry.o
obj-y       += exception.o
obj-y       += interrupt.o
obj-y       += crt0.o
#obj-y       += lowlevel_init.o
#obj-y      += board.o
obj-y       += timer.o
obj-y       += cache.o
