#
# SPDX-License-Identifier:	GPL-2.0+
#

# Machine directory name.  This list is sorted alphanumerically
# by CONFIG_* macro name.

head-y := arch/csky/cpu/$(CPU)/start.o

libs-y += arch/csky/cpu/
libs-y += arch/csky/cpu/$(CPU)/
libs-y += arch/csky/lib/

